// ════════════════════════════════════════════════════════════
//  EMOJI MAP — English & Afrikaans vocabulary
//  Words not found here fall back to a random themed icon.
//  Add entries here when a word comes up with no icon.
// ════════════════════════════════════════════════════════════

const EMOJI_MAP = {

    // ── ANIMALS ──────────────────────────────────────────────
    "ant": "🐜",        "mier": "🐜",
    "bat": "🦇",        "vlermuis": "🦇",
    "bear": "🐻",       "beer": "🐻",
    "bee": "🐝",        "by": "🐝",
    "bird": "🐦",       "voël": "🐦",
    "bug": "🐛",        "gogga": "🐛",
    "bull": "🐂",       "bul": "🐂",
    "butterfly": "🦋",  "skoenlapper": "🦋",
    "cat": "🐱",        "kat": "🐱",
    "chick": "🐥",      "kuiken": "🐥",
    "chicken": "🐔",    "hoender": "🐔",
    "cow": "🐮",        "koei": "🐮",
    "crab": "🦀",       "krap": "🦀",
    "crocodile": "🐊",  "krokodil": "🐊",
    "deer": "🦌",       "takbok": "🦌",
    "dog": "🐶",        "hond": "🐶",
    "dolphin": "🐬",    "dolfyn": "🐬",
    "donkey": "🫏",     "donkie": "🫏",
    "duck": "🦆",       "eend": "🦆",
    "eagle": "🦅",      "arend": "🦅",
    "elephant": "🐘",   "olifant": "🐘",
    "fish": "🐟",       "vis": "🐟",
    "fly": "🪰",        "vlieg": "🪰",
    "fox": "🦊",        "jakkals": "🦊",
    "frog": "🐸",       "padda": "🐸",
    "giraffe": "🦒",    "kameelperd": "🦒",
    "goat": "🐐",       "bok": "🐐",
    "gorilla": "🦍",    "gorilla": "🦍",
    "hen": "🐓",        "hen": "🐓",
    "hippo": "🦛",      "seekoei": "🦛",
    "horse": "🐴",      "perd": "🐴",
    "jellyfish": "🪼",  "jelvisvis": "🪼",
    "kangaroo": "🦘",   "kangaroe": "🦘",
    "lamb": "🐑",       "lam": "🐑",
    "lion": "🦁",       "leeu": "🦁",
    "monkey": "🐒",     "aap": "🐒",
    "mouse": "🐭",      "muis": "🐭",
    "octopus": "🐙",    "seekat": "🐙",
    "owl": "🦉",        "uil": "🦉",
    "parrot": "🦜",     "papegaai": "🦜",
    "penguin": "🐧",    "pikkewyn": "🐧",
    "pig": "🐷",        "vark": "🐷",
    "rabbit": "🐰",     "haas": "🐰",
    "rat": "🐀",        "rot": "🐀",
    "rhino": "🦏",      "renoster": "🦏",
    "shark": "🦈",      "haai": "🦈",
    "sheep": "🐑",      "skaap": "🐑",
    "snake": "🐍",      "slang": "🐍",
    "spider": "🕷️",    "spinnekop": "🕷️",
    "tiger": "🐯",      "tier": "🐯",
    "turtle": "🐢",     "skilpad": "🐢",
    "whale": "🐋",      "walvis": "🐋",
    "wolf": "🐺",       "wolf": "🐺",
    "worm": "🪱",       "wurm": "🪱",
    "zebra": "🦓",      "sebra": "🦓",

    // ── FOOD & DRINK ─────────────────────────────────────────
    "apple": "🍎",      "appel": "🍎",
    "avocado": "🥑",    "avokado": "🥑",
    "banana": "🍌",     "piesang": "🍌",
    "bread": "🍞",      "brood": "🍞",
    "butter": "🧈",     "botter": "🧈",
    "cake": "🎂",       "koek": "🎂",
    "candy": "🍬",      "lekker": "🍬",
    "carrot": "🥕",     "wortel": "🥕",
    "cheese": "🧀",     "kaas": "🧀",
    "cherry": "🍒",     "kers": "🍒",
    "chicken": "🍗",
    "chocolate": "🍫",  "sjokolade": "🍫",
    "coffee": "☕",     "koffie": "☕",
    "corn": "🌽",       "mielies": "🌽",
    "drop": "💧",       "druppel": "💧",
    "egg": "🥚",        "eier": "🥚",
    "flour": "🌾",      "meel": "🌾",
    "grape": "🍇",      "druif": "🍇",
    "honey": "🍯",      "heuning": "🍯",
    "ice cream": "🍦",  "roomys": "🍦",
    "juice": "🧃",      "sap": "🧃",
    "lemon": "🍋",      "suurlemoen": "🍋",
    "meat": "🥩",       "vleis": "🥩",
    "melon": "🍈",      "spanspek": "🍈",
    "milk": "🥛",       "melk": "🥛",
    "mushroom": "🍄",   "sampioen": "🍄",
    "orange": "🍊",     "lemoen": "🍊",
    "peanut": "🥜",     "grondboontjie": "🥜",
    "pear": "🍐",       "peer": "🍐",
    "peach": "🍑",      "perske": "🍑",
    "pineapple": "🍍",  "pynappel": "🍍",
    "pizza": "🍕",
    "potato": "🥔",     "aartappel": "🥔",
    "rice": "🍚",       "rys": "🍚",
    "salt": "🧂",       "sout": "🧂",
    "soup": "🍲",       "sop": "🍲",
    "strawberry": "🍓", "aarbei": "🍓",
    "sugar": "🍬",      "suiker": "🍬",
    "sweet": "🍬",
    "tea": "☕",        "tee": "☕",
    "tomato": "🍅",     "tamatie": "🍅",
    "water": "💧",
    "watermelon": "🍉", "waatlemoen": "🍉",

    // ── NATURE ───────────────────────────────────────────────
    "beach": "🏖️",     "strand": "🏖️",
    "cloud": "☁️",     "wolk": "☁️",
    "earth": "🌍",      "aarde": "🌍",
    "fire": "🔥",       "vuur": "🔥",
    "flood": "🌊",      "vloed": "🌊",
    "flower": "🌸",     "blom": "🌸",
    "forest": "🌲",     "woud": "🌲",
    "grass": "🌿",      "gras": "🌿",
    "ice": "🧊",        "ys": "🧊",
    "island": "🏝️",    "eiland": "🏝️",
    "lake": "🏞️",      "meer": "🏞️",
    "leaf": "🍃",       "blaar": "🍃",
    "lightning": "⚡",  "weerlig": "⚡",
    "moon": "🌙",       "maan": "🌙",
    "mountain": "⛰️",  "berg": "⛰️",
    "mud": "🟫",        "modder": "🟫",
    "rain": "🌧️",      "reën": "🌧️",
    "rainbow": "🌈",    "reënboog": "🌈",
    "river": "🏞️",     "rivier": "🏞️",
    "rock": "🪨",       "klip": "🪨",
    "sand": "🏜️",      "sand": "🏜️",
    "sea": "🌊",        "see": "🌊",
    "seed": "🌱",       "saad": "🌱",
    "sky": "🌤️",       "lug": "🌤️",
    "snow": "❄️",       "sneeu": "❄️",
    "star": "⭐",       "ster": "⭐",
    "storm": "⛈️",     "storm": "⛈️",
    "sun": "☀️",        "son": "☀️",
    "thunder": "⚡",    "donder": "⚡",
    "tree": "🌳",       "boom": "🌳",
    "volcano": "🌋",    "vulkaan": "🌋",
    "waterfall": "🌊",  "waterval": "🌊",
    "weather": "⛅",    "weer": "⛅",
    "wind": "💨",       "wind": "💨",

    // ── BODY ─────────────────────────────────────────────────
    "arm": "💪",
    "back": "🔙",
    "blood": "🩸",      "bloed": "🩸",
    "bone": "🦴",
    "brain": "🧠",      "brein": "🧠",
    "ear": "👂",        "oor": "👂",
    "eye": "👁️",       "oog": "👁️",
    "face": "😊",       "gesig": "😊",
    "finger": "☝️",    "vinger": "☝️",
    "foot": "🦶",       "voet": "🦶",
    "hair": "💇",       "hare": "💇",
    "hand": "✋",       "hand": "✋",
    "head": "🗣️",      "kop": "🗣️",
    "heart": "❤️",     "hart": "❤️",
    "knee": "🦵",       "knie": "🦵",
    "leg": "🦵",        "been": "🦵",
    "lip": "👄",        "lip": "👄",
    "mouth": "👄",      "mond": "👄",
    "muscle": "💪",     "spier": "💪",
    "neck": "🧣",       "nek": "🧣",
    "nose": "👃",       "neus": "👃",
    "skin": "🫁",       "vel": "🩹",
    "stomach": "🫃",    "maag": "🫃",
    "throat": "🗣️",    "keel": "🗣️",
    "toe": "🦶",        "toon": "🦶",
    "tooth": "🦷",      "tand": "🦷",

    // ── PEOPLE & FAMILY ──────────────────────────────────────
    "baby": "👶",       "baba": "👶",
    "boy": "👦",        "seun": "👦",
    "brother": "👦",    "broer": "👦",
    "child": "🧒",      "kind": "🧒",
    "cousin": "👦",     "neef": "👦",
    "doctor": "👨‍⚕️", "dokter": "👨‍⚕️",
    "father": "👨",     "pa": "👨",
    "friend": "🤝",     "vriend": "🤝",
    "girl": "👧",       "meisie": "👧",
    "grandma": "👵",    "ouma": "👵",
    "grandpa": "👴",    "oupa": "👴",
    "king": "🤴",       "koning": "🤴",
    "man": "👨",
    "mother": "👩",     "ma": "👩",
    "prince": "🤴",     "prins": "🤴",
    "princess": "👸",   "prinses": "👸",
    "queen": "👸",      "koningin": "👸",
    "sister": "👧",     "suster": "👧",
    "teacher": "👩‍🏫","juffrou": "👩‍🏫",   "meneer": "👨‍🏫",
    "woman": "👩",      "vrou": "👩",

    // ── HOME & OBJECTS ───────────────────────────────────────
    "bag": "👜",        "sak": "👜",
    "ball": "⚽",       "bal": "⚽",
    "bed": "🛏️",       "bed": "🛏️",
    "bell": "🔔",       "klok": "🔔",
    "book": "📚",       "boek": "📚",
    "bottle": "🍼",     "bottel": "🍼",
    "box": "📦",        "boks": "📦",
    "brush": "🪥",      "borsel": "🪥",
    "bucket": "🪣",     "emmer": "🪣",
    "candle": "🕯️",    "kers": "🕯️",
    "chair": "🪑",      "stoel": "🪑",
    "clock": "⏰",      "horlosie": "⏰",
    "comb": "🪮",       "kam": "🪮",
    "cup": "🍵",        "koppie": "🍵",
    "door": "🚪",       "deur": "🚪",
    "drum": "🥁",       "trom": "🥁",
    "flag": "🚩",       "vlag": "🚩",
    "fork": "🍴",       "vurk": "🍴",
    "glass": "🥛",      "glas": "🥛",
    "glue": "🧴",       "gom": "🧴",
    "guitar": "🎸",     "kitaar": "🎸",
    "hammer": "🔨",     "hamer": "🔨",
    "house": "🏠",      "huis": "🏠",
    "key": "🔑",        "sleutel": "🔑",
    "knife": "🔪",      "mes": "🔪",
    "lamp": "💡",       "lamp": "💡",
    "mirror": "🪞",     "spieël": "🪞",
    "paper": "📄",      "papier": "📄",
    "pen": "🖊️",       "pen": "🖊️",
    "pencil": "✏️",     "potlood": "✏️",
    "phone": "📱",      "foon": "📱",
    "piano": "🎹",      "klavier": "🎹",
    "plate": "🍽️",     "bord": "🍽️",
    "pot": "🍲",        "pot": "🍲",
    "ribbon": "🎀",     "lint": "🎀",
    "ruler": "📏",
    "scissors": "✂️",   "skêr": "✂️",
    "silk": "🎀",
    "soap": "🧼",       "seep": "🧼",
    "spoon": "🥄",      "lepel": "🥄",
    "table": "🪑",      "tafel": "🪑",
    "thread": "🧵",     "draad": "🧵",
    "torch": "🔦",      "flits": "🔦",
    "toy": "🪀",        "speelgoed": "🪀",
    "umbrella": "☂️",   "sambreel": "☂️",
    "window": "🪟",     "venster": "🪟",

    // ── SCHOOL & LEARNING ────────────────────────────────────
    "class": "🏫",      "klas": "🏫",
    "crayon": "🖍️",
    "lesson": "📖",     "les": "📖",
    "paint": "🎨",      "verf": "🎨",
    "school": "🏫",     "skool": "🏫",
    "test": "📝",       "toets": "📝",

    // ── TRANSPORT ────────────────────────────────────────────
    "bike": "🚲",       "fiets": "🚲",
    "boat": "⛵",       "boot": "⛵",
    "bridge": "🌉",     "brug": "🌉",
    "bus": "🚌",
    "car": "🚗",        "motor": "🚗",
    "helicopter": "🚁", "helikopter": "🚁",
    "plane": "✈️",      "vliegtuig": "✈️",
    "road": "🛣️",      "pad": "🛣️",
    "rocket": "🚀",     "vuurpyl": "🚀",
    "ship": "🚢",       "skip": "🚢",
    "train": "🚂",      "trein": "🚂",
    "truck": "🚛",      "vragmotor": "🚛",

    // ── CLOTHING ─────────────────────────────────────────────
    "coat": "🧥",       "jas": "🧥",
    "dress": "👗",      "rok": "👗",
    "glove": "🧤",      "handskoen": "🧤",
    "hat": "🎩",        "hoed": "🎩",
    "jacket": "🧥",     "baadjie": "🧥",
    "scarf": "🧣",      "serp": "🧣",
    "shoes": "👟",      "skoene": "👟",
    "shirt": "👕",      "hemp": "👕",
    "sock": "🧦",       "kous": "🧦",
    "shorts": "🩳",     "kortbroek": "🩳",

    // ── COLOURS ──────────────────────────────────────────────
    "black": "🖤",      "swart": "🖤",
    "blue": "💙",       "blou": "💙",
    "brown": "🟫",      "bruin": "🟫",
    "gold": "🥇",       "goud": "🥇",
    "green": "🍀",      "groen": "🍀",
    "grey": "🩶",       "grys": "🩶",
    "orange": "🟠",
    "pink": "🩷",       "pienk": "🩷",
    "purple": "💜",     "pers": "💜",
    "red": "❤️",        "rooi": "❤️",
    "silver": "🥈",     "silwer": "🥈",
    "white": "🤍",      "wit": "🤍",
    "yellow": "💛",     "geel": "💛",

    // ── ACTIONS ──────────────────────────────────────────────
    "clap": "👏",       "klap": "👏",
    "climb": "🧗",      "klim": "🧗",
    "cook": "👨‍🍳",   "kook": "👨‍🍳",
    "cry": "😢",        "huil": "😢",
    "dance": "💃",      "dans": "💃",
    "draw": "🎨",       "teken": "🎨",
    "drink": "🥤",      "drink": "🥤",
    "drive": "🚗",      "ry": "🚗",
    "eat": "🍽️",       "eet": "🍽️",
    "fall": "🍂",       "val": "🍂",
    "fly": "✈️",        "vlieg": "✈️",
    "free": "🕊️",      "vry": "🕊️",
    "grab": "🤏",       "gryp": "🤏",
    "grow": "🌱",       "groei": "🌱",
    "jump": "🦘",       "spring": "🦘",
    "laugh": "😂",      "lag": "😂",
    "live": "🌱",       "leef": "🌱",
    "play": "🎮",       "speel": "🎮",
    "read": "📖",       "lees": "📖",
    "run": "🏃",        "hardloop": "🏃",
    "sing": "🎤",       "sing": "🎤",
    "sit": "🪑",        "sit": "🪑",
    "sleep": "😴",      "slaap": "😴",
    "smile": "😊",      "glimlag": "😊",
    "stop": "🛑",       "stop": "🛑",
    "swim": "🏊",       "swem": "🏊",
    "think": "🤔",      "dink": "🤔",
    "throw": "🎯",      "gooi": "🎯",
    "walk": "🚶",       "stap": "🚶",
    "wash": "🧼",       "was": "🧼",
    "write": "✏️",      "skryf": "✏️",

    // ── FEELINGS ─────────────────────────────────────────────
    "angry": "😠",      "kwaad": "😠",
    "bored": "😑",
    "brave": "💪",      "dapper": "💪",
    "calm": "😌",       "kalm": "😌",
    "excited": "🤩",    "opgewonde": "🤩",
    "happy": "😊",      "bly": "😊",
    "kind": "🤗",       "vriendelik": "🤗",
    "love": "❤️",       "liefde": "❤️",
    "proud": "🏆",      "trots": "🏆",
    "sad": "😢",        "hartseer": "😢",
    "scared": "😨",     "bang": "😨",
    "sick": "🤒",       "siek": "🤒",
    "strong": "💪",     "sterk": "💪",
    "tired": "😴",      "moeg": "😴",

    // ── PLACES ───────────────────────────────────────────────
    "city": "🏙️",      "stad": "🏙️",
    "farm": "🚜",       "plaas": "🚜",
    "garden": "🌻",     "tuin": "🌻",
    "hospital": "🏥",   "hospitaal": "🏥",
    "jungle": "🌴",     "oerwoud": "🌴",
    "market": "🛒",     "mark": "🛒",
    "park": "🌳",
    "shop": "🛍️",      "winkel": "🛍️",
    "zoo": "🦁",        "dieretuin": "🦁",

    // ── NUMBERS & SHAPES ─────────────────────────────────────
    "circle": "⭕",     "sirkel": "⭕",
    "heart": "❤️",
    "square": "🟥",     "vierkant": "🟥",
    "star": "⭐",
    "triangle": "🔺",   "driehoek": "🔺",
    "one": "1️⃣",       "een": "1️⃣",
    "two": "2️⃣",       "twee": "2️⃣",
    "three": "3️⃣",     "drie": "3️⃣",
    "four": "4️⃣",      "vier": "4️⃣",
    "five": "5️⃣",      "vyf": "5️⃣",
    "six": "6️⃣",       "ses": "6️⃣",
    "seven": "7️⃣",     "sewe": "7️⃣",
    "eight": "8️⃣",     "agt": "8️⃣",
    "nine": "9️⃣",      "nege": "9️⃣",
    "ten": "🔟",        "tien": "🔟",

    // ── MISC ─────────────────────────────────────────────────
    "birthday": "🎂",   "verjaarsdag": "🎂",
    "cool": "😎",
    "day": "☀️",        "dag": "☀️",
    "dream": "💭",      "droom": "💭",
    "gift": "🎁",       "geskenk": "🎁",
    "help": "🆘",       "help": "🆘",
    "home": "🏠",       "tuis": "🏠",
    "magic": "✨",      "magie": "✨",
    "money": "💰",      "geld": "💰",
    "music": "🎵",      "musiek": "🎵",
    "name": "🏷️",      "naam": "🏷️",
    "news": "📰",       "nuus": "📰",
    "night": "🌙",      "nag": "🌙",
    "party": "🎉",      "partytjie": "🎉",
    "photo": "📸",      "foto": "📸",
    "prize": "🏆",      "prys": "🏆",
    "safe": "🔒",       "veilig": "🔒",
    "secret": "🤫",     "geheim": "🤫",
    "story": "📖",      "storie": "📖",
    "time": "⏰",       "tyd": "⏰",
    "today": "📅",      "vandag": "📅",
    "trip": "🧳",       "reis": "🧳",
    "wish": "⭐",       "wens": "⭐",
    "world": "🌍",      "wêreld": "🌍",
    "year": "📅",       "jaar": "📅",

};
